### ISSUE TITLE
4.4.3 Release contains 4.2.4 msi file

### ISSUE THREAD

**Issue by metawops** [fischertechnik/FT-TXT#14]
My TXT has firmware 4.2.4.0 and I wanted to upgrade it to the next available, which is 4.4.3 (because updating it to the latest firmware didn‘t work).
However, the 4.4.3 release here contains the 4.2.4 .msi file which, indeed, contains ROBOPro 4.2.4 and the 4.2.4.0 firmware for the TXT.
The next release, 4.4.4 does contain the 4.4.4 version of ROBOPro but I couldn‘t install the 4.4.4 firmware onto my 4.2.4 TXT, either.
So it would be nice if there actually was the 4.4.3 version as an msi file so I could try this.

**Comment by AlexanderSteiger** [comment]
firmware 4.4.3 is not a stable release, please use the latest firmware release.

This repository exists only for >= 4.4.3. This is because you can find the earlier firmware 4.2.4 msi in the first version published at github
