### ISSUE TITLE
MQTT 

### ISSUE THREAD

**Issue by atikeryazilim** [fischertechnik/FT-TXT#7]
We purchased Factory Simulation 9V. We updated all TXT controller for version 4.5.1.
How can we receive data by Mqtt broker server.There is no information about that.

**Comment by AlexanderSteiger** [comment]
You need a MQTT client that sends the data. You can not get data from the TXT Controller with an MQTT Broker alone. Of course, you can use MQTT if you implement your own C / C ++ program, which then reads out the TXT controller data and then sends it via MQTT. The programs included in https://github.com/fischertechnik/txt_training_factory are intended for the following product https://www.fischertechnik.de/en/service/elearning/teaching/lernfabrik-4.
